platform :ios, '7.0'

pod 'AFJSONRPCClient', '~> 1.0.0'
pod 'Mantle', '~> 1.3.1'
pod 'UICKeyChainStore', '~> 1.0.4'

pod 'Appirater', '~> 2.0.2'
pod 'UIActionSheet+Blocks', '~> 0.7'
pod 'UIAlertView+Blocks', '~> 0.7'
pod 'MBProgressHUD', '~> 0.8'
pod 'MPColorTools', '~> 1.4.1'
pod 'RETableViewManager', '~> 1.5.7'
